spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://khebkeam:ON9dKbL6C0qOs1WJ5n1k-7IbYL1a5ZPq@tuffi.db.elephantsql.com:5432/khebkeam"
spring.datasource.username: "khebkeam"
spring.datasource.password: "ON9dKbL6C0qOs1WJ5n1k-7IbYL1a5ZPq"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"