#
#   This is the core configuration for a configuration service.  I have two examples here:
#
#       -  A configuration service which completelty loads the configuration for the services
#          from the local file server of the config service.
#
#       -  A configuraton service that uses a git-based repository to read the files from
#
####################################
#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://<your-git-path>/
#          searchPaths: chamadotecnico, filafilme, filme, historico, ranking, usuario
#          username: native-cloud-apps
#          password: 0ffended


####
#Classpath and file-based solution
####
server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/chamadotecnico, file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/filafilme, file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/historico, file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/ranking, file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/usuario, file:///C:/java/repositorio/NetflixConfiguration/src/main/resources/config/filme