spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://capgctrs:XEGaWX4LbIHzUk9kacvDSK7_o5wIIdbo@tuffi.db.elephantsql.com:5432/capgctrs"
spring.datasource.username: "capgctrs"
spring.datasource.password: "XEGaWX4LbIHzUk9kacvDSK7_o5wIIdbo"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"