spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://ozmktjkf:0iEwp9T4SXVx9HLs_k9T6TYWqZrwQYlQ@tuffi.db.elephantsql.com:5432/ozmktjkf"
spring.datasource.username: "ozmktjkf"
spring.datasource.password: "0iEwp9T4SXVx9HLs_k9T6TYWqZrwQYlQ"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"