spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgres://zopgrgsc:R5XsT9R3CVNxLJdhJhghy8iyDbc01EzV@tuffi.db.elephantsql.com:5432/zopgrgsc"
spring.datasource.username: "zopgrgsc"
spring.datasource.password: "R5XsT9R3CVNxLJdhJhghy8iyDbc01EzV"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"